name: Update airports.json from Google Sheet

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Google Sheet and convert to JSON
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1_C3d1l17AdGDFNAzdtCJZgRsf_EaII_x8275ggrRmoA/gviz/tq?tqx=out:csv" -o data.csv
          echo "import csv, json" > convert.py
          echo "with open('data.csv') as f:" >> convert.py
          echo "    reader = csv.DictReader(f)" >> convert.py
          echo "    rows = list(reader)" >> convert.py
          echo "with open('airports.json', 'w') as f:" >> convert.py
          echo "    json.dump(rows, f, indent=2)" >> convert.py
          python3 convert.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          touch .nojekyll
          git add airports.json .nojekyll
          git commit -m "Update airports.json and disable Jekyll" || echo "No changes to commit"
          git push
